// <auto-generated />
namespace LibraryManagment.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddGivenBooks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGivenBooks));
        
        string IMigrationMetadata.Id
        {
            get { return "202303231007233_AddGivenBooks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
